---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 5
  template:
    metadata:
      name: jobspec
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpine
          image: alpine
          args:
            - sleep
            - 1d