---
  - name: install lamp on ubuntu
    host: all
    become: yes
    tasks:
      - name: update package and install apache
        apt:
          name: apache2
          state: present 
          update_cache: yes
      - name: update package and install php
        apt: 
          name: 
            - php
            - libapache2-mod-php
            - php-mysql
          state: present
      - name: copy the info.php
        ansible.builtin.copy:
          src: info.php
          dest: /var/www/html/info.php
        notify:
          - restart apache2
    handlers:
      - name: restart apache2
        ansible.builtin.systemd:
          name: apache2
  