---
  - name: install lamp server on redhat
    hosts: all
    become: yes
    tasks:
      - name: update and install httpd
        ansible.builtin.yum: 
          name: httpd
          state: present
          update_cache: yes
      - name: enable and restart httpd
        ansible.builtin.systemd:
          name: httpd
          enable: true
          state: started
      - name: install php server
        ansible.builtin.yum:
          name: php
          update_cache: true
          state: present
      - name: start httpd service and enable
        ansible.builtin.systemd:
          name: httpd
          enabled: yes
          state: started 
      - name: copy info.php 
        ansible.builtin.copy:
          src: info.php 
          dest: /var/www/html/info.php
      - name: restart httpd service 
        ansible.builtin.systemd:
          name: httpd
          state: restarted
  




        