---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate: 
    metadata:
      name: cronjob
    spec:
      backoffLimit: 3
      template:
        metadata:
          name: job 
        spec: 
          containers:
            - name: alpine
              image: alpine
              args:
                - sleep
                - 2s     
          restartPolicy: OnFailure
