---
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  backoffLimit: 3
  template:
    metadata:
      name: jobhttpd
    spec:
      restartPolicy: OnFailure
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80