--- 
apiVersion: v1
kind: Pod 
metadata:
  name: chandu33
spec:
  restartPolicy: OnFailure
  containers:
    - name: vinod
      image: alpine
      args:
        - sleep
        - 5s
    - name: apache
      image: httpd 
      ports:
        - containerPort: 80