---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-alpine
spec: 
  containers:
    - name: nginx1
      image: nginx  
      ports: 
        - containerPort: 80
    - name: alpine1
      image: alpine
      args:
        - sleep
        - 1d