

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic
  region: us-east-2

nodeGroups:
  - name: basic
    instanceType: t2.large
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key

