---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
spec:
  minReadySeconds: 1
  replicas: 3
  selector:
    matchLabels: 
      app: jenkins-rs
  template: 
    metadata:
      name: jemkins-pod
      labels:
        app: jenkins-rs
    spec:
      containers:
        - name: jenkins
          image : jenkins/jenkins
          ports:
            - containerPort: 8080
        - name: alpine
          image: alpine
          args:
            - sleep
            - 5s        
               
                  
    